services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000 # Updated to match the port in the Dockerfile
    ports:
      - "4000:4000" # Updated to expose the app on port 4000
    volumes:
      - .:/app
    command: ["bun", "start"]
